Add typescript typings
sindresorhus/split-on-first pull request #1
Opened 2019-02-10 03:27 UTC by coolreader18

2019-02-10 08:12 UTC, sindresorhus commented
Thanks for creating a TypeScript definition. 🙌 Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

2019-02-14 00:06 UTC, coolreader18 commented
To follow that, should I put `exports.default = export;` in `index.js`?

2019-02-14 07:34 UTC, sindresorhus requested changes

2019-02-14 07:34 UTC, sindresorhus commented on index.d.ts
> +declare function splitOnFirst(string: string, separator: string): [string, string?];
You don't need to declare. You can just export it directly.

2019-02-14 07:34 UTC, sindresorhus commented on index.d.ts
> + * @returns The string split on the separator, if possible.
This is unclear. It makes it seem it returns the string. Should be clearer.

2019-03-02 18:46 UTC, sindresorhus commented
Ping :)

2019-04-27 15:08 UTC, sindresorhus commented
Closing in favor of #4

2019-04-27 15:08 UTC, closed without merging